### ISSUE TITLE
RtD name

### ISSUE THREAD

**Issue by henryiii** [LovelyBuggies/Nino-hist#7]
It looks like your `.readthedocs.yml` is actually named `readthedocs.yml` (no beginning dot). I wonder if that could be an issue?

**Comment by LovelyBuggies** [comment]
It might be. But according to RtD user guide: https://docs.readthedocs.io/en/stable/config-file/index.html#configuration-file

> In addition to using the admin panel of your project to configure your project, you can use a configuration file in the root of your project. The configuration file can be named as:
> 
> - `readthedocs.yml`
> - `readthedocs.yaml`
> - `.readthedocs.yml`
> - `.readthedocs.yaml`

**Comment by henryiii** [comment]
Yep, this name is allowed then.
